### ISSUE TITLE
[BE] ERD 그리기

### ISSUE THREAD

**Issue by leejohy-0223** [leejohy-0223/airbnb#1]
## 💡 issue
- 논리적 ERD 그리기
- 물리적 ERD 그리기

## 📝 todo
- [X] 논리적 ERD 모델링
![image](https://user-images.githubusercontent.com/62360009/169813954-34b71aab-b58a-47ac-8ec8-6d3a1e81c0ab.png)

- [X] 물리적 ERD 모델링
![image](https://user-images.githubusercontent.com/62360009/169814111-0e676075-bc08-4977-a20e-2db834297509.png)

**Comment by zbqmgldjfh** [comment]
수고하셨습니다 루시드!!
